Oui24bit pin
binarymaster/3WiFi pull request #31
Opened 2017-03-19 22:55 UTC by kcdtv

Little contribution from spain and other place using the data base of WPS PIN (bash script created in 2012). The data base has been updated over the years and it is freely available here: [https://www.wifi-libre.com/topic-626-base-de-datos-wpspin-original-open-source-actualizada.html](url)
Notice that the algorithm was found in 2012 by  ZaoChunsheng and published in the script ComputePIN-C83A35 (for more information check [)](http://hellocow.cn/2012/04/get-the-pin-in-router-mac-address-start-with-c83a35-00b00c-081075/) 
It is known as "Zao algorithm", at least in some part of the globe :smiley_cat: 
Al this data are 100% safe/complete and I checked them personally. They've been collected over five year with contribution from users from several forums,. mainly Spanish and French.
Some more will come. 
Cheers!

2017-03-19 23:02 UTC, binarymaster commented
Hello!

Thanks for the patch, I'll review its contents to make sure of compatibility with WPS PIN generator.

2017-03-19 23:08 UTC, binarymaster requested changes
Review is complete, please fix your changes according to the comments.

Also it would be great to rebase all your commits into single one.

Many thanks!

2017-03-19 23:08 UTC, binarymaster commented on wpspin.html
> +  00:B0:0C:XX:XX:XX
Please fix these `:XX:XX:XX` to lowercase `:xx:xx:xx`.

2017-03-19 23:08 UTC, binarymaster commented on wpspin.html
> +  D8:6C:E9:XX:XX:XX
Please sort OUIs in alphabetic order (`DC:` should be after `D8:`).

2017-03-19 23:08 UTC, binarymaster commented on wpspin.html
> +  80:1F:02:XX:XX:XX
Please sort OUIs in alphabetic order (`80:` should be before `E4:`).

2017-03-19 23:08 UTC, binarymaster commented on wpspin.html
> +</body>
This change is really not needed, please leave it without new line.

2017-03-20 19:08 UTC, kcdtv commented
HI! 
  It has been a very long and hard day for me so I won't be able to do the corrections today and to add the others bSSID.
Let's do it differently, instead of correcting this request i will propose you a clean one applying your recommendations and adding all bssid at once as you suggested . 
See you soon.

2017-03-20 19:10 UTC, binarymaster commented
Well, it could be done by rebasing and force pushing to your branch.

But if you want to create another pull request, alright then.

2017-03-20 19:14 UTC, kcdtv commented
HI!
It has been a very long and hard day for me so I won't be able to do the corrections today and to add the others bSSID.
Let's do it differently, instead of correcting this request i will propose you a clean one applying your recommendations and adding all bssid at once as you suggested .
See you soon

2017-03-21 17:45 UTC, kcdtv commented
> Well, it could be done by rebasing and force pushing to your branch.

I'll do it like this, thanks for the suggestion. 
 I have very crazy and buzzy days until Thursday and there is a very huge amount of OUI from HG566a devices that need to be organized alphanumerically.  I won't probably be able to present the request before Thursday, sorry about that. See you soon!

2017-03-21 18:44 UTC, binarymaster commented
No problem!

Maybe this tool would be useful in your case:
http://textmechanic.com/text-tools/basic-text-tools/sort-text-lines/

2017-03-26 13:30 UTC, kcdtv commented
i presented a new request with all bssids included so i close this one.

2017-03-26 13:30 UTC, closed without merging